config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts, only: [:new, :create, :index]
  root to: "posts#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :posts, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      flash.notice = "Post, '#{@post.title}' created!"
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar bg-dark">
<div class="container">
<%= link_to "Club House", root_path, class: "font-weight-bold" %>
<p class="navbar-text float-right">
<% if user_signed_in? %>
<strong class="text-primary mr-3">No of post: <%= current_user.posts.count %></strong>
 <span class= "text-primary"> Logged in as</span> <strong class="text-primary"><%= current_user.name %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>
</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
  <div class = "container">
  <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<div class= "container">
    <h1 class="font-weight-bold">Create a Post</h1>

<%= form_for @post do |f| %>
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %><br>
    <%= f.label :body %><br>
    <%= f.text_area :body, class: "form-control"%><br>
    <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>
<%= link_to "<< Back to Posts List", root_path, class: 'btn btn-primary mt-2'%>
</div>

app/views/posts/index.html.erb
<div class = "container jumbotron text-center ">
  <div class="card">
    <div class="card-header">
      <p class= "font-weight-bold text-muted">All Posts</p>
    </div>
   <div class="card-body"> 
    <% @posts.each do |post| %> 
      <p class= "font-weight-bold">
        <%= post.title %>
      </p> 
      <p class= "text-muted">
        <%= post.body %>
      </p> 
      <% if current_user %> 
        <p><strong>Created by:</strong> <%= post.user.name %></p> 
      <% end %> 
      <hr> 
    <% end %> 
  </div>
  <% if current_user %> 
    <div><%= link_to 'Create a post', new_post_path, class: "mb-3 btn btn-primary" %> </div> 
  <% end %>

</div>
  

app/views/posts/new.html.erb
<%= render 'form' %>